#!/bin/bash
# ll_mpirun_script (C) 2015 Wolfgang Tichy
# needed for submitjob 

# save date and time in $now
now=$(date +%Y%m%d%H%M)

# make the name of the script we create to run with llsubmit
runscript=$jobname.$now.sh

# write a script
echo writing script:
echo $runscript
cat > $runscript << EOL
###########################################################################
#!/bin/bash
# some stuff for llsubmit
#@ job_type = bluegene
#@ job_name = $jobname
#@ environment = COPY_ALL
#@ wall_clock_limit = $walltime
#@ bg_size = $nodes
#@ bg_connectivity = MESH
#@ account_no = $account
#### #@ notification = always
#### #@ notify_user = sebastiano.bernuzzi@gmail.com
EOL

# WRITE RUNSCRIPT - STEP01
echo step01
cat >> $runscript << EOL
#
# step 01
#
#@ output = $jobname.$now.o01
#@ error = $jobname.$now.e01
#### #@ step_name = $jobname.$now.01
#@ step_name = step01
#@ bg_size = $nodes
#@ queue
EOL

# WRITE RUNSCRIPT - STEPS WITH DEPENDENCIES
for i in `seq -w 02 $njobs`
do
printf -v j "%02d" $((i-1))
echo step$i
cat >> $runscript << EOL
#
# step $i
#
#@ output = $jobname.$now.o$i
#@ error = $jobname.$now.e$i
#### #@ step_name = $jobname.$now.$i
#@ step_name = step$i
#@ dependency = ( $jobname.$now.$j == 0 )
#@ bg_size = $nodes
#@ queue
EOL
done

# ACTUAL RUN COMMAND
cat >> $runscript << EOL
###########################################################################

# Replace some parts of $MPIRUN and $MPIBOOT with the local env vars here:
#replace string $PBS_NODEFILE with content of env var $PBS_NODEFILE
#MPIBOOT=${MPIBOOT/\$PBS_NODEFILE/$PBS_NODEFILE}
#MPIRUN=${MPIRUN/\$PBS_NODEFILE/$PBS_NODEFILE}
#MPIHALT=${MPIHALT/\$PBS_NODEFILE/$PBS_NODEFILE}

# tell me what's happening:
echo "======================================================================"
echo $submitjob
echo "----------------------------------------------------------------------"
echo "nodes = $nodes"
echo "ppn = $ppn"
echo "procs = $procs"
echo "memory = $memory"
echo "walltime = $walltime"
echo "queue = $queue"
echo "njobs = $njobs"
echo "jobname = $jobname"
echo "command = $command"
echo "parfile = $parfile"
echo
echo "MPIBOOT = $MPIBOOT"
echo "MPIRUN = $MPIRUN"
echo "MPIHALT = $MPIHALT"
echo
echo "OMP_NUM_THREADS = $OMP_NUM_THREADS"
echo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-"
echo The current working directory is:
pwd
echo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-"

echo
echo "======================================================================"

time $MPIRUN

echo "======================================================================"
echo
EOL

# the script we write ends above EOL

# now run this script with llsubmit
echo running:  
echo llsubmit $runscript
llsubmit $runscript
