#!/bin/bash
# lsf_mpirun_script (C) 2006 Wolfgang Tichy
# needed for submitjob

# Replace some parts of $MPIRUN with the local env vars here:
 #replace string $LSB_HOSTS in MPIRUN with content of env var $LSB_HOSTS
MPIRUN=${MPIRUN/\$LSB_HOSTS/$LSB_HOSTS}

# tell me what's happening:
echo "======================================================================"
echo $submitjob
echo "----------------------------------------------------------------------"
echo "nodes = $nodes"
echo "ppn = $ppn"
echo "walltime = $walltime"
echo "queue = $queue"
echo "jobname = $jobname"
echo "command = $command"
echo "parfile = $parfile"
echo
echo "MPIRUN = $MPIRUN"
echo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-"
echo The master node of this job is `hostname`
echo The working directory is `echo $LS_SUBCWD`
echo The node file is $LSB_HOSTS
echo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-"
echo This job runs on the following nodes:
echo `cat $LSB_HOSTS`
echo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-"

# make LSF go to current dir
echo going to $LS_SUBCWD
cd $LS_SUBCWD

echo
echo "Job started on `hostname` at `date`"
echo "======================================================================"

time $MPIRUN 

echo "======================================================================"
echo "Job Ended at `date`"
echo
